"""Backward-compatible imports for production Level-1 prompts."""

from .level1.prompts import (
    EDWARD_OPTION_CODE_V1_SYSTEM_PROMPT,
    EDWARD_OPTION_CODE_V2_SYSTEM_PROMPT,
    EDWARD_OBJECTIVE_V1_SYSTEM_PROMPT,
    LIVE_STATE_V3_SYSTEM_PROMPT,
    LIVE_STATE_V3_USER_INSTRUCTION,
    MINIMAL_V1_SYSTEM_PROMPT,
    MINIMAL_V1_USER_INSTRUCTION,
    PROMPT_STYLES,
    SYSTEM_PROMPT,
    USER_INSTRUCTION,
    build_image_messages,
    encode_png,
    image_count,
    live_state_instruction,
    png_data_url,
    png_sha256,
    prompt_text,
)

__all__ = [
    "EDWARD_OPTION_CODE_V1_SYSTEM_PROMPT",
    "EDWARD_OPTION_CODE_V2_SYSTEM_PROMPT",
    "EDWARD_OBJECTIVE_V1_SYSTEM_PROMPT",
    "LIVE_STATE_V3_SYSTEM_PROMPT",
    "LIVE_STATE_V3_USER_INSTRUCTION",
    "MINIMAL_V1_SYSTEM_PROMPT",
    "MINIMAL_V1_USER_INSTRUCTION",
    "PROMPT_STYLES",
    "SYSTEM_PROMPT",
    "USER_INSTRUCTION",
    "build_image_messages",
    "encode_png",
    "image_count",
    "live_state_instruction",
    "png_data_url",
    "png_sha256",
    "prompt_text",
]
